# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import institutes.fields
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('subdomain', models.CharField(max_length=255, unique=True)),
                ('db_settings', institutes.fields.JSONField(default={}, verbose_name='DB Settings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
